"""Version control for the *workspace*: what it tracks, and when it commits.

The ledger is append-only, so a collected run cannot be un-recorded by anything
in this system working as designed. What is genuinely at risk is everything
around it -- `notes/`, a project's `MEMORY.md` and `PLAN.md`, the pipeline code
the agent is editing, a report's `.tex` -- all of which are ordinary files that
an ordinary mistake can truncate or delete. `agent.checkpointing_option` covers
the span of one session; this is what covers the span of a project.

Four decisions worth knowing before changing anything here.

**It is initialised deliberately and never automatically.** Creating a git
repository inside somebody's folder is a side effect they did not ask for, and a
research workspace can already be inside one -- a shared drive, a dotfiles
repository, somebody's own versioning. `initialise` is a command and a setup
step; everything after it is automatic.

**It refuses to run when the workspace is the installation.** The default
workspace *is* the checkout, and Grad's own source is already versioned there:
auto-committing would put a user's notebooks on the same branch as upstream's
releases and turn every `grad update` into a merge, which is the exact failure
`tools/workspace.py:move` exists to prevent. The refusal names `move`.

**It commits at events, not at writes.** A commit per file write would produce
hundreds a session and a history nobody can read. The boundaries are the ones
the system already treats as meaningful -- a run collected, a verdict recorded,
a project's documents regenerated -- so the log reads as a record of the
research rather than of the editor.

**Nothing here may fail a caller.** `checkpoint` is called just after the ledger
has been written, and a git that is missing, wedged, or mid-rebase must not turn
a successful collect into a failed command. Every entry point returns a result
document with an `error` field instead of raising.

There is no remote, and adding one is not a small change: pushing a research
workspace publishes the pipeline, the data pointers and any credential that
found its way into a notebook. The ignore list below is written to make that
survivable if it is ever added, but the argument in `config/grad.toml` for
`is_private = true` applies with more force here.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from core import paths, version

log = logging.getLogger("grad.vcs")

#: Set on the repository at `initialise`, and the thing `enabled()` tests.
#:
#: A marker in the repository's own config rather than a file in the workspace:
#: it travels with the repository, it cannot be mistaken for research, and it
#: answers the question that actually matters -- "is this a repository Grad made
#: and may therefore commit to" -- rather than "is there a `.git` here", which
#: is true of a workspace somebody keeps inside their own dotfiles.
MARKER = "grad.workspace"

#: The commit identity used when the machine has none configured.
#:
#: Only when there is none: a user with a global `user.email` gets their own,
#: because these are commits in their research folder and attributing them to a
#: tool would be wrong. Git refuses to commit at all without one, and "your
#: research is not being checkpointed because git has never been configured on
#: this machine" is a bad way to find out.
FALLBACK_NAME = "Grad"
FALLBACK_EMAIL = "grad@localhost"

#: What a workspace repository tracks, and what it must not.
#:
#: Lifted from the repository's own `.gitignore`, which had already worked this
#: out: the JSONL ledgers are tracked *because* they are the source of truth and
#: are meant to be human-diffable, and the SQLite indexes beside them are not,
#: because they are derived from the JSONL and rebuildable at any time. The two
#: rules that matter most are the last two -- a corpus of downloaded papers is
#: large and re-fetchable, and a credential is never a thing to commit.
IGNORE = """\
# Written by `grad-workspace vcs init`. Safe to edit: nothing regenerates it.
#
# The JSONL ledgers ARE tracked, deliberately. They are the source of truth for
# every run, expectation and verdict, they are append-only, and they diff
# usefully line by line -- which is the whole reason this repository is worth
# having. The SQLite files beside them are derived from those ledgers and are
# rebuilt on demand, so they would only ever be merge conflicts.
ledger/ledger.sqlite
ledger/ledger.sqlite-*
data/corpus.sqlite
data/corpus.sqlite-*

# Downloaded papers: large, and re-fetchable from the arXiv ids in the ledger.
data/papers/

# Collected run artifacts. The run *record* is in ledger/runs.jsonl and is
# tracked; the checkpoints and logs it points at can be hundreds of megabytes.
ledger/runs/

# Figures are outputs. They are regenerated by re-running the notebook that drew
# them, and a binary that changes on every run is the worst thing to put in a
# diff. A figure that made it into a paper is referenced from reports/ instead.
figures/

# Live machine state, not research: a Lab server's port, pid and token; the
# selected project, which is one machine's choice rather than a fact about the
# work; JupyterLab's own generated runtime files.
data/lab/
data/wiki/
ledger/.current_project
config/jupyter/lab/
config/jupyter/migrated

# LaTeX build byproducts. The .tex, claims.json and references.bib ARE tracked:
# they are the checkable artifacts.
reports/**/*.pdf
reports/**/*.aux
reports/**/*.bbl
reports/**/*.blg
reports/**/*.fls
reports/**/*.log
reports/**/*.out
reports/**/*.fdb_latexmk
reports/**/claims.tex

# Never, under any circumstances. Credentials live in the OS credential store;
# this is belt and braces for the one that gets written to a file by a library
# that did not ask.
.env
*.pem
credentials.json
kaggle.json
.grad-workspace.json

# Python and editor litter.
__pycache__/
*.py[cod]
.ipynb_checkpoints/
.venv/
venv/
"""


def root() -> Path:
    return paths.root()


def _git(*args: str, timeout: float = 15.0) -> str | None:
    return version.git(*args, cwd=root(), timeout=timeout)


def _result(*args: str, timeout: float = 15.0) -> Any:
    return version.git_result(*args, cwd=root(), timeout=timeout)


def is_repository() -> bool:
    """Is the workspace the top of a git repository?

    `--show-toplevel` rather than `--git-dir`, and the comparison is the point:
    a workspace *inside* somebody's repository answers yes to "are you in a
    repository" and must still answer no here. Committing there would sweep up
    whatever else that repository holds.
    """
    top = _git("rev-parse", "--show-toplevel")
    if not top:
        return False
    try:
        return Path(top.strip()).resolve() == root().resolve()
    except OSError:
        return False


def enabled() -> bool:
    """May `checkpoint` commit here? Never raises."""
    try:
        if root().resolve() == paths.install_dir().resolve():
            return False
    except OSError:
        return False
    if not is_repository():
        return False
    return (_git("config", "--local", "--get", MARKER) or "").strip() == "true"


def _refuse_if_installation() -> str | None:
    """The one refusal that is about the *layout* rather than about git."""
    try:
        same = root().resolve() == paths.install_dir().resolve()
    except OSError:
        return None
    if not same:
        return None
    return (
        "the workspace is the installation folder, and versioning it would put your "
        "research on the same branch as Grad's own source -- which is what makes an "
        "update a merge. Move the research out first."
    )


def initialise(*, identity: bool = True) -> dict[str, Any]:
    """Create the repository, write the ignore list, make the first commit.

    Idempotent in the way that matters: a workspace that is already a marked
    repository is reported as such and nothing is rewritten. A workspace that is
    a repository somebody *else* made is refused rather than adopted -- the
    marker is what separates the two, and quietly taking over a repository is
    not a thing to do to somebody's folder.
    """
    out: dict[str, Any] = {
        "root": str(root()),
        "created": False,
        "already": False,
        "error": None,
        "fix": None,
    }
    refusal = _refuse_if_installation()
    if refusal:
        out["error"] = refusal
        out["fix"] = "python -m tools.workspace move --to <folder>"
        return out

    if version.git("--version", cwd=root()) is None:
        out["error"] = "git is not available on this machine"
        out["fix"] = "install git, or leave the workspace unversioned"
        return out

    if is_repository():
        if enabled():
            out["already"] = True
            return out
        out["error"] = (
            "the workspace is already a git repository that Grad did not create. "
            "Adopting it would mean committing to a history that is not ours."
        )
        out["fix"] = f"git -C {root()} config --local {MARKER} true   # to opt in deliberately"
        return out

    if not _ok(_result("init")):
        out["error"] = "git init failed"
        return out
    _git("config", "--local", MARKER, "true")
    if identity:
        _ensure_identity()

    _write_ignore(root() / ".gitignore")

    out["created"] = True
    first = checkpoint("workspace initialised", force=True)
    out["commit"] = first.get("commit")
    out["error"] = first.get("error")
    return out


#: Fences the block this module manages, so it can be added to a file somebody
#: else wrote without being written twice on the next `init`.
IGNORE_BEGIN = "# --- grad: managed, do not edit between these markers ---"
IGNORE_END = "# --- end grad ---"


def _ok(result: Any) -> bool:
    """Did a git command actually succeed?

    `None` means it never ran; a non-zero return code means it ran and refused,
    and the two were being conflated. `if _result("init") is None` treated a
    *failed* `git init` as a success and went on to configure and commit into a
    directory that is not a repository -- which fails again, later, somewhere
    less obvious.
    """
    return result is not None and getattr(result, "returncode", 1) == 0


def _write_ignore(path: Path) -> None:
    """Put the managed rules in, without touching anybody else's.

    A workspace can already have a `.gitignore` -- somebody's own, or one left
    by a checkout it used to be. The first version skipped the file entirely in
    that case, which meant `.env`, `kaggle.json` and `data/papers/` were not
    excluded and the very first checkpoint committed them. A credential in a
    commit survives the file being deleted, so this is the one rule in here
    worth being careful about.

    Appended between markers rather than merged line by line, so a second `init`
    replaces the block instead of duplicating it, and so anything the user wrote
    is visibly not ours.
    """
    block = f"{IGNORE_BEGIN}\n{IGNORE}{IGNORE_END}\n"
    try:
        existing = path.read_text(encoding="utf-8") if path.exists() else ""
    except OSError:
        existing = ""
    if IGNORE_BEGIN in existing:
        head, _, rest = existing.partition(IGNORE_BEGIN)
        _, _, tail = rest.partition(IGNORE_END)
        existing = head + tail.lstrip("\n")
    prefix = existing.rstrip("\n") + "\n\n" if existing.strip() else ""
    path.write_text(prefix + block, encoding="utf-8")


def _ensure_identity() -> None:
    """Give git an identity only if the machine has not got one."""
    if (_git("config", "--get", "user.email") or "").strip():
        return
    _git("config", "--local", "user.name", FALLBACK_NAME)
    _git("config", "--local", "user.email", FALLBACK_EMAIL)


def checkpoint(reason: str, *, force: bool = False) -> dict[str, Any]:
    """Commit whatever has changed, if anything has. Never raises.

    Called from the paths that have just recorded something durable, so the two
    properties it needs are that it is cheap when there is nothing to do and
    that it cannot fail its caller. A `collect` that fetched results, wrote the
    run record and then reported failure because git was mid-rebase would be a
    strictly worse outcome than an uncommitted workspace.

    `force` is for the first commit, where "nothing has changed" is true of the
    index and false of the world.
    """
    out: dict[str, Any] = {"committed": False, "commit": None, "error": None, "reason": reason}
    try:
        if not force and not enabled():
            return out
        staged_ok = _result("add", "-A")
        if not _ok(staged_ok):
            # Stop here rather than committing what happened to be staged
            # already: an `add` that refused (a lock file, a permission, an
            # index mid-rebase) means the commit below would record a state
            # nobody chose.
            out["error"] = (getattr(staged_ok, "stderr", "") or "").strip() or "git add failed"
            return out
        # `--porcelain` on the *index*: `diff --cached --quiet` exits 1 when
        # there is something staged, which is the cheap way to ask "is this
        # commit going to be empty" without parsing anything.
        staged = _result("diff", "--cached", "--quiet")
        if staged is not None and staged.returncode == 0 and not force:
            return out
        message = _message(reason)
        commit = _result("commit", "-m", message, "--no-verify")
        if commit is None or commit.returncode != 0:
            detail = (getattr(commit, "stderr", "") or "").strip()
            # An empty commit is not an error -- it is the race where something
            # else committed between the check above and here.
            if "nothing to commit" in detail or "nothing added" in detail:
                return out
            out["error"] = detail or "git commit failed"
            return out
        out["committed"] = True
        out["commit"] = (_git("rev-parse", "--short", "HEAD") or "").strip() or None
    except Exception as exc:  # noqa: BLE001 - see the docstring
        log.debug("workspace checkpoint failed", exc_info=True)
        out["error"] = f"{type(exc).__name__}: {exc}"
    return out


def _message(reason: str) -> str:
    """One line, and the project it belongs to when there is one.

    Deliberately plain. The log is read to answer "what did the afternoon of the
    fourteenth actually establish", and a subject line naming the event and the
    project answers it without opening the diff.
    """
    text = " ".join(str(reason or "checkpoint").split())[:120]
    try:
        from core import budget  # noqa: PLC0415

        project = budget.current_project()
    except Exception:  # noqa: BLE001 - a message is not worth failing over
        project = None
    return f"{project}: {text}" if project else text


def status() -> dict[str, Any]:
    """What the workspace repository is, and what is uncommitted in it."""
    out: dict[str, Any] = {
        "root": str(root()),
        "repository": False,
        "enabled": False,
        "commits": 0,
        "dirty": [],
        "head": None,
        "error": _refuse_if_installation(),
    }
    if not is_repository():
        return out
    out["repository"] = True
    out["enabled"] = enabled()
    out["head"] = (_git("rev-parse", "--short", "HEAD") or "").strip() or None
    count = _git("rev-list", "--count", "HEAD")
    out["commits"] = int(count.strip()) if count and count.strip().isdigit() else 0
    dirty = _git("status", "--porcelain")
    out["dirty"] = [line for line in (dirty or "").splitlines() if line.strip()]
    return out


def history(limit: int = 20) -> list[dict[str, str]]:
    """The last few checkpoints, newest first. Empty on any failure."""
    raw = _git("log", f"-{max(1, int(limit))}", "--format=%h%x1f%aI%x1f%s")
    entries = []
    for line in (raw or "").splitlines():
        parts = line.split("\x1f")
        if len(parts) == 3:
            entries.append({"commit": parts[0], "at": parts[1], "subject": parts[2]})
    return entries
