"""The JupyterLab half of the design, generated from the same tokens.

The notebook window is a real Lab iframe on its own port, so it is a different
origin and its interior cannot be styled from the host page. The handoff asks
for a **pinned theme extension**. This does the same job with a `custom.css`
file instead, and the trade is worth stating plainly:

* A theme extension means npm, TypeScript, a cookiecutter, a build step in
  packaging, and a rebuild on every JupyterLab minor -- the JupyterLab 3→4 break
  is exactly what killed the Tabnine extension, and the `lab` extra pins every
  version precisely because of it.
* JupyterLab 4 loads `{JUPYTER_CONFIG_DIR}/custom/custom.css` when started with
  `--custom-css`. `tools/lab.py` already sets `JUPYTER_CONFIG_DIR` to
  `config/jupyter`, so this is a plain file and one flag.

The cost of the cheaper path is that `custom.css` cannot register a *named*
theme, so `overrides.json` selects `JupyterLab Light` and this sheet re-tokens
it, rather than selecting a theme called "Grad Paper". Everything the handoff
lists -- `--jp-layout-color*`, `--jp-border-color*`,
`--jp-cell-editor-background`, the font families, `.jp-InputArea-prompt`,
`.jp-OutputArea-output`, `.jp-RenderedText` -- is set either way.

Generated rather than hand-written so the notebook interior cannot drift from
the chrome above it: `tests/test_ui_theme.py` fails if the file on disk stops
matching `stylesheet()`.

    python -m ui.jupyter_theme --write
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

from core import paths
from ui import tokens

BANNER = "/* generated by ui/jupyter_theme.py — edit the tokens, not this file */"


def target() -> Path:
    """Where JupyterLab looks, given the config dir `tools/lab.py` sets."""
    return paths.root() / "config" / "jupyter" / "custom" / "custom.css"


def repo_path() -> Path:
    """The version-controlled copy.

    Module-relative rather than `paths.root()`-derived: this file is part of the
    repository, not of a workspace, and `GRAD_ROOT` points at a temp directory
    under test. The two agree in every real run because `GRAD_ROOT` is the
    checkout.
    """
    return Path(__file__).resolve().parents[1] / "config" / "jupyter" / "custom" / "custom.css"


#: Which JupyterLab base each palette re-tokens. `custom.css` cannot register a
#: named theme, so it overrides whichever base is selected -- and the base has to
#: match, or dark defaults sit under cream overrides in every corner the sheet
#: below does not name. There are a lot of those corners: the file browser, the
#: command palette, the status bar, every menu.
LAB_BASE: dict[str, str] = {
    "light": "JupyterLab Light",
    "dark": "JupyterLab Dark",
}


def stylesheet(theme: str | None = None) -> str:
    c = tokens.palette(theme)
    return f"""{BANNER}

/* ------------------------------------------------------------------ tokens */
:root {{
  --jp-layout-color0: {c['paper']};
  --jp-layout-color1: {c['paper']};
  --jp-layout-color2: {c['paper-sunk']};
  --jp-layout-color3: {c['desk']};
  --jp-layout-color4: {c['desk']};

  --jp-inverse-layout-color0: {c['ink']};
  --jp-inverse-layout-color1: {c['ink']};
  --jp-inverse-layout-color2: {c['ink']};
  --jp-inverse-layout-color3: {c['muted']};

  --jp-ui-font-color0: {c['ink']};
  --jp-ui-font-color1: {c['ink']};
  --jp-ui-font-color2: {c['muted']};
  --jp-ui-font-color3: {c['muted-2']};
  --jp-content-font-color0: {c['ink']};
  --jp-content-font-color1: {c['ink']};
  --jp-content-font-color2: {c['muted']};
  --jp-content-font-color3: {c['muted-2']};

  --jp-border-color0: {c['ink']};
  --jp-border-color1: {c['ink']};
  --jp-border-color2: {c['rule-soft']};
  --jp-border-color3: {c['rule-soft']};
  --jp-border-width: 2px;
  --jp-border-radius: 0px;

  --jp-brand-color0: {c['ink']};
  --jp-brand-color1: {c['attention']};
  --jp-brand-color2: {c['attention']};
  --jp-brand-color3: {c['attention']};
  --jp-accent-color1: {c['verified']};
  --jp-warn-color0: {c['attention']};
  --jp-warn-color1: {c['attention']};
  --jp-error-color0: {c['broken']};
  --jp-error-color1: {c['broken']};
  --jp-success-color1: {c['verified']};
  --jp-info-color1: {c['link']};

  --jp-cell-editor-background: {c['paper-raised']};
  --jp-cell-editor-border-color: {c['ink']};
  --jp-cell-editor-active-background: {c['paper-raised']};
  --jp-cell-editor-active-border-color: {c['ink']};
  --jp-cell-prompt-not-active-opacity: 0.55;
  --jp-cell-inprompt-font-color: {c['ink']};
  --jp-cell-outprompt-font-color: {c['link']};

  --jp-code-font-family: {tokens.FONT_MONO};
  --jp-code-font-size: 13.5px;
  --jp-code-line-height: 1.7;
  --jp-ui-font-family: {tokens.FONT_SANS};
  --jp-ui-font-size1: 13px;
  --jp-content-font-family: {tokens.FONT_SANS};
  --jp-content-font-size1: 15px;
  --jp-content-line-height: 1.58;

  --jp-toolbar-background: {c['paper-sunk']};
  --jp-toolbar-border-color: {c['ink']};
  --jp-toolbar-box-shadow: none;
  --jp-notebook-padding: 0px;

  --jp-rendermime-error-background: {c['broken-tint']};
  --jp-rendermime-table-row-background: {c['paper']};
  --jp-rendermime-table-row-hover-background: {c['row-alt']};

  /* Radius 0 everywhere, and no blur shadows anywhere. */
  --jp-elevation-z0: none;
  --jp-elevation-z1: none;
  --jp-elevation-z2: none;
  --jp-elevation-z4: none;
  --jp-elevation-z6: none;
  --jp-elevation-z8: none;
  --jp-elevation-z12: none;
  --jp-elevation-z16: none;
  --jp-elevation-z20: none;
  --jp-elevation-z24: none;
}}

/* -------------------------------------------------------------- structure */
body, .jp-Notebook, .jp-NotebookPanel {{ background: {c['paper']}; }}
* {{ border-radius: 0 !important; box-shadow: none !important; }}

.jp-Toolbar {{
  background: {c['paper-sunk']};
  border-bottom: 2px solid {c['ink']};
  min-height: 30px;
}}

/* The gutter: paper-sunk, a 2px right rule, right-aligned mono prompt. */
.jp-InputArea-prompt, .jp-OutputArea-prompt {{
  background: {c['paper-sunk']};
  border-right: 2px solid {c['ink']};
  font-family: {tokens.FONT_MONO};
  font-size: 12px;
  color: {c['ink']};
  text-align: right;
  padding-right: 9px;
}}

/* The 6px state stripe, driven by what Lab already knows about the cell. */
.jp-Cell {{
  border-left: {tokens.STRIPE_WIDTH} solid transparent;
  border-bottom: 1px solid {c['rule-soft']};
  padding: 0;
}}
.jp-Cell.jp-mod-selected {{ border-left-color: {c['ink']}; background: {c['paper']}; }}
.jp-Cell:has(.jp-OutputArea-output[data-mime-type="application/vnd.jupyter.stderr"]) {{
  border-left-color: {c['broken']};
}}
.jp-Cell:has(.jp-InputArea-prompt:empty) {{ border-left-color: {c['attention']}; }}

.jp-CodeCell .jp-Editor {{
  background: {c['paper-raised']};
  border: 0;
}}
.jp-InputArea-editor {{ border: 0; border-left: 1px solid {c['rule-soft']}; }}

/* -------------------------------------------------------------- markdown */
.jp-RenderedHTMLCommon h1,
.jp-RenderedHTMLCommon h2,
.jp-RenderedHTMLCommon h3,
.jp-RenderedHTMLCommon h4 {{
  font-family: {tokens.FONT_SERIF};
  font-weight: 400;
  color: {c['ink']};
  margin: 14px 0 6px;
}}
.jp-RenderedHTMLCommon h1 {{ font-size: 30px; }}
.jp-RenderedHTMLCommon h2 {{ font-size: 21px; }}
.jp-RenderedHTMLCommon h3 {{ font-size: 19px; }}
.jp-RenderedHTMLCommon p {{ max-width: 74ch; }}
.jp-RenderedHTMLCommon a {{ color: {c['link']}; text-underline-offset: 2px; }}
.jp-RenderedHTMLCommon code {{ background: {c['paper-sunk']}; padding: 1px 4px; }}
.jp-RenderedHTMLCommon .MathJax_Display,
.jp-RenderedHTMLCommon mjx-container[display="true"] {{
  border: 2px solid {c['ink']};
  background: {c['paper-raised']};
  padding: 12px;
}}

/* ---------------------------------------------------------------- output */
.jp-OutputArea-output {{
  background: {c['paper']};
  font-family: {tokens.FONT_MONO};
  font-size: 12.5px;
}}
.jp-RenderedText {{
  font-family: {tokens.FONT_MONO};
  font-size: 12.5px;
  line-height: 1.7;
  color: {c['ink']};
}}
.jp-RenderedText[data-mime-type="application/vnd.jupyter.stderr"] {{
  background: {c['broken-tint']};
  border-left: {tokens.STRIPE_WIDTH} solid {c['broken']};
  color: {c['broken-ink']};
}}

.jp-RenderedHTMLCommon table {{ border-collapse: collapse; font-family: {tokens.FONT_MONO}; }}
.jp-RenderedHTMLCommon thead th {{
  background: {c['fill']};
  color: {c['fill-ink']};
  text-align: left;
  padding: 7px 9px;
  font-size: 10px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}}
.jp-RenderedHTMLCommon tbody td {{ border-bottom: 1px solid {c['rule-soft']}; padding: 7px 9px; }}
.jp-RenderedHTMLCommon tbody tr:nth-child(even) {{ background: {c['row-alt']}; }}

.jp-RenderedImage img {{ border: 2px solid {c['ink']}; background: {c['paper-raised']}; }}

/* ----------------------------------------------------------------- chrome */
.jp-SideBar, .jp-FileBrowser, .jp-DirListing {{ background: {c['paper-sunk']}; }}
.jp-DirListing-item.jp-mod-selected {{ background: {c['fill']}; color: {c['fill-ink']}; }}
.jp-Toolbar-item .jp-ToolbarButtonComponent:hover {{ background: {c['paper-sunk']}; }}
.lm-TabBar-tab.lm-mod-current {{
  background: {c['fill']} !important;
  color: {c['fill-ink']} !important;
  border: 0;
}}
.lm-TabBar-tab {{ background: {c['paper-sunk']}; border-right: 1px solid {c['rule-soft']}; }}
.jp-Statusbar, #jp-bottom-panel {{
  background: {c['fill']};
  color: {c['fill-ink']};
  font-family: {tokens.FONT_MONO};
  font-size: 11px;
}}

/* CodeMirror token colours, matching the host's code blocks exactly. */
.cm-editor .cm-content {{ font-family: {tokens.FONT_MONO}; font-size: 13.5px; }}
.cm-keyword, .cm-atom {{ color: {c['ink']}; font-weight: 700; }}
.cm-def, .cm-variable-2, .cm-property {{ color: {c['link']}; }}
.cm-number, .cm-string {{ color: {c['literal']}; }}
.cm-comment {{ color: {c['muted-2']}; font-style: italic; }}
.cm-operator, .cm-punctuation {{ color: {c['muted']}; }}
.cm-editor .cm-ruler {{ border-right: 1px dashed {c['rule-mid']}; }}
.cm-cursor {{ border-left: 2px solid {c['ink']}; }}
.cm-editor .cm-selectionBackground {{ background: {c['attention']} !important;
                                       color: {c['on-attention']} !important; }}
"""


def write(path: Path | None = None, theme: str | None = None) -> Path:
    path = path or repo_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(stylesheet(theme), encoding="utf-8")
    return path


def install(theme: str | None = None) -> dict[str, Any]:
    """Put the sheet and the base-theme selection where Lab will read them.

    Called by `tools/lab.py` before the server starts, and it closes two things
    at once.

    The first is the theme: `custom.css` re-tokens a base rather than
    registering one, so the base has to match the palette or Lab's own chrome --
    file browser, command palette, menus, every corner the sheet does not name
    -- keeps the defaults of the wrong one.

    The second predates the theme and is the larger of the two.
    `JUPYTER_CONFIG_DIR` is `paths.root()/config/jupyter` -- the *workspace* --
    and only the checkout has that directory in it. The installer asks for a
    workspace separate from the code and gives good reasons for it, and every
    install that took the advice has been starting Lab with `--custom-css`
    aimed at a file that does not exist and `--ServerApp.config_file` at another
    one. That is stock JupyterLab inside Grad's chrome, and the server config
    that sets the framing headers never loading -- exactly the seam this module
    was written to close, on the recommended layout.

    So the shipped files are seeded when they are absent, the way
    `core/paths.py:_shipped` resolves the other three code-adjacent paths, and
    only `custom.css` is rewritten every time: it is generated, and the other two
    are documents someone may have edited.

    Never raises: a workspace whose config directory cannot be written is one
    where Lab should still start, unstyled.
    """
    import shutil  # noqa: PLC0415

    from core import jsonl  # noqa: PLC0415

    chosen = str(theme or tokens.DEFAULT_THEME).lower()
    if chosen not in LAB_BASE:
        chosen = tokens.DEFAULT_THEME
    result: dict[str, Any] = {
        "theme": chosen, "written": [], "seeded": [], "skipped": None, "error": None,
    }
    try:
        config_dir = target().parent.parent
        shipped_dir = repo_path().parent.parent
        config_dir.mkdir(parents=True, exist_ok=True)

        # Seeded, not overwritten. `jupyter_server_config.py` reads
        # GRAD_UI_ORIGIN and GRAD_LAB_PORT so the framing headers and the port
        # cannot drift apart; a workspace without it has no framing policy at
        # all, which is a security-relevant absence rather than a cosmetic one.
        if shipped_dir != config_dir:
            for name in ("jupyter_server_config.py", "overrides.json"):
                source, destination = shipped_dir / name, config_dir / name
                if source.is_file() and not destination.exists():
                    shutil.copyfile(source, destination)
                    result["seeded"].append(str(destination))

        # The workspace *is* the checkout in a default install, and then
        # `target()` is the tracked, generated `custom.css` that
        # `test_ui_theme.py` asserts equals `stylesheet()`. Writing the dark
        # sheet there would dirty the repository and fail that test for anyone
        # who had switched theme -- so the pair is left exactly as committed.
        #
        # Left *as a pair*, which is the part worth stating: skipping only the
        # sheet while still switching the base theme would put dark JupyterLab
        # defaults under a cream override, which is the mismatch `LAB_BASE`
        # exists to prevent. Both are skipped, and the caller is told, because a
        # notebook that stays cream in a dark workspace is otherwise a silent
        # disagreement. Keeping the research in its own folder -- which the
        # installer already recommends and the README already argues for -- is
        # what makes a dark Lab available.
        if config_dir == shipped_dir:
            result["skipped"] = (
                "the workspace is the installation, where config/jupyter/custom/custom.css is "
                "a tracked generated file; JupyterLab keeps the light theme here"
            )
            return result

        sheet = target()
        write(sheet, chosen)
        result["written"].append(str(sheet))

        # Merged rather than replaced: `overrides.json` carries the handoff's
        # 88-column ruler and whatever else has been set in it, and rewriting the
        # file to hold one key would silently drop the rest.
        overrides_path = config_dir / "overrides.json"
        current = jsonl.read_json(overrides_path)
        if not isinstance(current, dict):
            current = jsonl.read_json(shipped_dir / "overrides.json") or {}
        themes = dict(current.get("@jupyterlab/apputils-extension:themes") or {})
        themes["theme"] = LAB_BASE[chosen]
        current["@jupyterlab/apputils-extension:themes"] = themes
        jsonl.write_json(overrides_path, current)
        result["written"].append(str(overrides_path))
    except Exception as exc:  # noqa: BLE001 - see the docstring
        result["error"] = f"{type(exc).__name__}: {exc}"
    return result


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if "--write" in argv:
        print(f"wrote {write()}")
        return 0
    print(stylesheet())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
