"""The JupyterLab half of the design, generated from the same tokens.

The notebook window is a real Lab iframe on its own port, so it is a different
origin and its interior cannot be styled from the host page. The handoff asks
for a **pinned theme extension**. This does the same job with a `custom.css`
file instead, and the trade is worth stating plainly:

* A theme extension means npm, TypeScript, a cookiecutter, a build step in
  packaging, and a rebuild on every JupyterLab minor -- the JupyterLab 3→4 break
  is exactly what killed the Tabnine extension, and the `lab` extra pins every
  version precisely because of it.
* JupyterLab 4 loads `{JUPYTER_CONFIG_DIR}/custom/custom.css` when started with
  `--custom-css`. `tools/lab.py` already sets `JUPYTER_CONFIG_DIR` to
  `config/jupyter`, so this is a plain file and one flag.

The cost of the cheaper path is that `custom.css` cannot register a *named*
theme, so `overrides.json` selects `JupyterLab Light` and this sheet re-tokens
it, rather than selecting a theme called "Grad Paper". Everything the handoff
lists -- `--jp-layout-color*`, `--jp-border-color*`,
`--jp-cell-editor-background`, the font families, `.jp-InputArea-prompt`,
`.jp-OutputArea-output`, `.jp-RenderedText` -- is set either way.

Generated rather than hand-written so the notebook interior cannot drift from
the chrome above it: `tests/test_ui_theme.py` fails if the file on disk stops
matching `stylesheet()`.

    python -m ui.jupyter_theme --write
"""

from __future__ import annotations

import sys
from pathlib import Path

from core import paths
from ui import tokens

BANNER = "/* generated by ui/jupyter_theme.py — edit the tokens, not this file */"


def target() -> Path:
    """Where JupyterLab looks, given the config dir `tools/lab.py` sets."""
    return paths.root() / "config" / "jupyter" / "custom" / "custom.css"


def repo_path() -> Path:
    """The version-controlled copy.

    Module-relative rather than `paths.root()`-derived: this file is part of the
    repository, not of a workspace, and `GRAD_ROOT` points at a temp directory
    under test. The two agree in every real run because `GRAD_ROOT` is the
    checkout.
    """
    return Path(__file__).resolve().parents[1] / "config" / "jupyter" / "custom" / "custom.css"


def stylesheet() -> str:
    c = tokens.COLOUR
    return f"""{BANNER}

/* ------------------------------------------------------------------ tokens */
:root {{
  --jp-layout-color0: {c['paper']};
  --jp-layout-color1: {c['paper']};
  --jp-layout-color2: {c['paper-sunk']};
  --jp-layout-color3: {c['desk']};
  --jp-layout-color4: {c['desk']};

  --jp-inverse-layout-color0: {c['ink']};
  --jp-inverse-layout-color1: {c['ink']};
  --jp-inverse-layout-color2: {c['ink']};
  --jp-inverse-layout-color3: {c['muted']};

  --jp-ui-font-color0: {c['ink']};
  --jp-ui-font-color1: {c['ink']};
  --jp-ui-font-color2: {c['muted']};
  --jp-ui-font-color3: {c['muted-2']};
  --jp-content-font-color0: {c['ink']};
  --jp-content-font-color1: {c['ink']};
  --jp-content-font-color2: {c['muted']};
  --jp-content-font-color3: {c['muted-2']};

  --jp-border-color0: {c['ink']};
  --jp-border-color1: {c['ink']};
  --jp-border-color2: {c['rule-soft']};
  --jp-border-color3: {c['rule-soft']};
  --jp-border-width: 2px;
  --jp-border-radius: 0px;

  --jp-brand-color0: {c['ink']};
  --jp-brand-color1: {c['attention']};
  --jp-brand-color2: {c['attention']};
  --jp-brand-color3: {c['attention']};
  --jp-accent-color1: {c['verified']};
  --jp-warn-color0: {c['attention']};
  --jp-warn-color1: {c['attention']};
  --jp-error-color0: {c['broken']};
  --jp-error-color1: {c['broken']};
  --jp-success-color1: {c['verified']};
  --jp-info-color1: {c['link']};

  --jp-cell-editor-background: {c['paper-raised']};
  --jp-cell-editor-border-color: {c['ink']};
  --jp-cell-editor-active-background: {c['paper-raised']};
  --jp-cell-editor-active-border-color: {c['ink']};
  --jp-cell-prompt-not-active-opacity: 0.55;
  --jp-cell-inprompt-font-color: {c['ink']};
  --jp-cell-outprompt-font-color: {c['link']};

  --jp-code-font-family: {tokens.FONT_MONO};
  --jp-code-font-size: 13.5px;
  --jp-code-line-height: 1.7;
  --jp-ui-font-family: {tokens.FONT_SANS};
  --jp-ui-font-size1: 13px;
  --jp-content-font-family: {tokens.FONT_SANS};
  --jp-content-font-size1: 15px;
  --jp-content-line-height: 1.58;

  --jp-toolbar-background: {c['paper-sunk']};
  --jp-toolbar-border-color: {c['ink']};
  --jp-toolbar-box-shadow: none;
  --jp-notebook-padding: 0px;

  --jp-rendermime-error-background: {c['broken-tint']};
  --jp-rendermime-table-row-background: {c['paper']};
  --jp-rendermime-table-row-hover-background: {c['row-alt']};

  /* Radius 0 everywhere, and no blur shadows anywhere. */
  --jp-elevation-z0: none;
  --jp-elevation-z1: none;
  --jp-elevation-z2: none;
  --jp-elevation-z4: none;
  --jp-elevation-z6: none;
  --jp-elevation-z8: none;
  --jp-elevation-z12: none;
  --jp-elevation-z16: none;
  --jp-elevation-z20: none;
  --jp-elevation-z24: none;
}}

/* -------------------------------------------------------------- structure */
body, .jp-Notebook, .jp-NotebookPanel {{ background: {c['paper']}; }}
* {{ border-radius: 0 !important; box-shadow: none !important; }}

.jp-Toolbar {{
  background: {c['paper-sunk']};
  border-bottom: 2px solid {c['ink']};
  min-height: 30px;
}}

/* The gutter: paper-sunk, a 2px right rule, right-aligned mono prompt. */
.jp-InputArea-prompt, .jp-OutputArea-prompt {{
  background: {c['paper-sunk']};
  border-right: 2px solid {c['ink']};
  font-family: {tokens.FONT_MONO};
  font-size: 12px;
  color: {c['ink']};
  text-align: right;
  padding-right: 9px;
}}

/* The 6px state stripe, driven by what Lab already knows about the cell. */
.jp-Cell {{
  border-left: {tokens.STRIPE_WIDTH} solid transparent;
  border-bottom: 1px solid {c['rule-soft']};
  padding: 0;
}}
.jp-Cell.jp-mod-selected {{ border-left-color: {c['ink']}; background: {c['paper']}; }}
.jp-Cell:has(.jp-OutputArea-output[data-mime-type="application/vnd.jupyter.stderr"]) {{
  border-left-color: {c['broken']};
}}
.jp-Cell:has(.jp-InputArea-prompt:empty) {{ border-left-color: {c['attention']}; }}

.jp-CodeCell .jp-Editor {{
  background: {c['paper-raised']};
  border: 0;
}}
.jp-InputArea-editor {{ border: 0; border-left: 1px solid {c['rule-soft']}; }}

/* -------------------------------------------------------------- markdown */
.jp-RenderedHTMLCommon h1,
.jp-RenderedHTMLCommon h2,
.jp-RenderedHTMLCommon h3,
.jp-RenderedHTMLCommon h4 {{
  font-family: {tokens.FONT_SERIF};
  font-weight: 400;
  color: {c['ink']};
  margin: 14px 0 6px;
}}
.jp-RenderedHTMLCommon h1 {{ font-size: 30px; }}
.jp-RenderedHTMLCommon h2 {{ font-size: 21px; }}
.jp-RenderedHTMLCommon h3 {{ font-size: 19px; }}
.jp-RenderedHTMLCommon p {{ max-width: 74ch; }}
.jp-RenderedHTMLCommon a {{ color: {c['link']}; text-underline-offset: 2px; }}
.jp-RenderedHTMLCommon code {{ background: {c['paper-sunk']}; padding: 1px 4px; }}
.jp-RenderedHTMLCommon .MathJax_Display,
.jp-RenderedHTMLCommon mjx-container[display="true"] {{
  border: 2px solid {c['ink']};
  background: {c['paper-raised']};
  padding: 12px;
}}

/* ---------------------------------------------------------------- output */
.jp-OutputArea-output {{
  background: {c['paper']};
  font-family: {tokens.FONT_MONO};
  font-size: 12.5px;
}}
.jp-RenderedText {{
  font-family: {tokens.FONT_MONO};
  font-size: 12.5px;
  line-height: 1.7;
  color: {c['ink']};
}}
.jp-RenderedText[data-mime-type="application/vnd.jupyter.stderr"] {{
  background: {c['broken-tint']};
  border-left: {tokens.STRIPE_WIDTH} solid {c['broken']};
  color: {c['broken-ink']};
}}

.jp-RenderedHTMLCommon table {{ border-collapse: collapse; font-family: {tokens.FONT_MONO}; }}
.jp-RenderedHTMLCommon thead th {{
  background: {c['ink']};
  color: {c['paper']};
  text-align: left;
  padding: 7px 9px;
  font-size: 10px;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}}
.jp-RenderedHTMLCommon tbody td {{ border-bottom: 1px solid {c['rule-soft']}; padding: 7px 9px; }}
.jp-RenderedHTMLCommon tbody tr:nth-child(even) {{ background: {c['row-alt']}; }}

.jp-RenderedImage img {{ border: 2px solid {c['ink']}; background: {c['paper-raised']}; }}

/* ----------------------------------------------------------------- chrome */
.jp-SideBar, .jp-FileBrowser, .jp-DirListing {{ background: {c['paper-sunk']}; }}
.jp-DirListing-item.jp-mod-selected {{ background: {c['ink']}; color: {c['paper']}; }}
.jp-Toolbar-item .jp-ToolbarButtonComponent:hover {{ background: {c['paper-sunk']}; }}
.lm-TabBar-tab.lm-mod-current {{
  background: {c['ink']} !important;
  color: {c['paper']} !important;
  border: 0;
}}
.lm-TabBar-tab {{ background: {c['paper-sunk']}; border-right: 1px solid {c['rule-soft']}; }}
.jp-Statusbar, #jp-bottom-panel {{
  background: {c['ink']};
  color: {c['paper']};
  font-family: {tokens.FONT_MONO};
  font-size: 11px;
}}

/* CodeMirror token colours, matching the host's code blocks exactly. */
.cm-editor .cm-content {{ font-family: {tokens.FONT_MONO}; font-size: 13.5px; }}
.cm-keyword, .cm-atom {{ color: {c['ink']}; font-weight: 700; }}
.cm-def, .cm-variable-2, .cm-property {{ color: {c['link']}; }}
.cm-number, .cm-string {{ color: {c['literal']}; }}
.cm-comment {{ color: {c['muted-2']}; font-style: italic; }}
.cm-operator, .cm-punctuation {{ color: {c['muted']}; }}
.cm-editor .cm-ruler {{ border-right: 1px dashed {c['rule-mid']}; }}
.cm-cursor {{ border-left: 2px solid {c['ink']}; }}
.cm-editor .cm-selectionBackground {{ background: {c['attention']} !important; }}
"""


def write(path: Path | None = None) -> Path:
    path = path or repo_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(stylesheet(), encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if "--write" in argv:
        print(f"wrote {write()}")
        return 0
    print(stylesheet())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
